{{- if and .Values.importAgents.enabled .Values.importAgents.servers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: import-agents-inventory
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
data:
  servers.yml: |
    servers:
    {{- .Values.importAgents.servers | toYaml | nindent 4 }}
{{- end }}
