{{- if .Values.instanceGroups.enabled }}
{{- if not .Values.clusterFulfillment.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
data:
  {{- range $key, $value := .Values.instanceGroups.cluster.config }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
type: Opaque
data: {}
{{- end }}
{{- if not .Values.networkFulfillment.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
data:
  {{- range $key, $value := .Values.instanceGroups.network.config }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: network-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
type: Opaque
data: {}
{{- end }}
{{- if not .Values.storageFulfillment.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-operations-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
data:
  {{- range $key, $value := .Values.instanceGroups.storage.config }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-operations-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
type: Opaque
data: {}
{{- end }}
{{- end }}
